version: 2
updates:
  - package-ecosystem: "npm"
    versioning-strategy: increase
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "gerardroche"
    assignees:
      - "gerardroche"
  - package-ecosystem: "github-actions"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "gerardroche"
    assignees:
      - "gerardroche"
